# Generated by Django 6.0.2 on 2026-03-12 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_generator_app', '0002_alter_device_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='link_generator_app.protectedlink'),
        ),
    ]
